### ISSUE TITLE
Feature Request: ability to create a minimal empty message

### ISSUE THREAD

**Issue by jeoffman** [domibies/HL7lite#10]
I would like a method "AddSegmentMSH()" that does not require any parameters so I can create a "minimal" HL7 segment and then add stuff as I go.

**Comment by jeoffman** [comment]
bump

**Comment by domibies** [comment]
Hey, thanks for you requests. I have incorporated them in the spring2024 branch. I’ll update the nuget by the end of next week.

**Comment by domibies** [comment]
merged changes with master branch and pushed v1.2.0 nuget
