### ISSUE TITLE
Bump test project to dotnet8 and remove references to unnecessary dependencies (Visual Studio "vulnerabilities" warning)

### ISSUE THREAD

**Issue by jeoffman** [domibies/HL7lite#4]
Proposal:
Simple bump of the unit tests to the latest LTS version of dotnet
Remove some unnecessary package references that make Visual Studio give a spooky if invalid warning:
![image](https://github.com/domibies/HL7lite/assets/7606177/93d54109-4a7f-40a3-8f61-d50a8cbf80ea)

**Comment by jeoffman** [comment]
bump

**Comment by domibies** [comment]
merged changes with master branch and pushed v1.2.0 nuget
