### ISSUE TITLE
add a few checks around internal HL7 path parsing, and throw proper HL7Exceptions

### ISSUE THREAD

**Issue by jeoffman** [domibies/HL7lite#8]
I stumbled onto a few cases where a System.NullReferenceException was being thrown due to accessing field/component/subcomponent indexes that are out of range so I thought I would suggest a fix for it.

This issue is not a "real" issue since many of the "catch" code is for System.Exception, but if you ever want to be more specific then it would be an issue.

**Comment by jeoffman** [comment]
bump

**Comment by domibies** [comment]
merged changes with master branch and pushed v1.2.0 nuget
